/* eslint-disable @typescript-eslint/no-var-requires */
const {
  withAndroidManifest,
  withMainActivity,
  withDangerousMod,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Config plugin: foreground service for AlphaPOS Operator Link.
 *
 * Call detection (react-native-call-detection) only fires while the app
 * process is alive. On a dedicated operator phone the app is backgrounded for
 * long stretches, so we run a started foreground service to keep the process
 * resident and the phone-state listener active.
 *
 * What this plugin does at prebuild:
 *   1. Adds the foreground-service + notification permissions to the manifest.
 *   2. Declares the `CallBridgeForegroundService` (dataSync type).
 *   3. Writes the Kotlin Service source into the generated Android project.
 *   4. Starts the service from MainActivity.onCreate so it runs for the app's
 *      lifetime (no JS<->native bridge required to start it).
 */

const SERVICE_NAME = 'CallBridgeForegroundService';
const SERVICE_TYPE = 'dataSync';

const FOREGROUND_PERMISSIONS = [
  'android.permission.FOREGROUND_SERVICE',
  'android.permission.FOREGROUND_SERVICE_DATA_SYNC',
  'android.permission.POST_NOTIFICATIONS',
];

function ensurePermission(androidManifest, name) {
  const manifest = androidManifest.manifest;
  if (!Array.isArray(manifest['uses-permission'])) {
    manifest['uses-permission'] = [];
  }
  const exists = manifest['uses-permission'].some(
    (perm) => perm.$ && perm.$['android:name'] === name
  );
  if (!exists) {
    manifest['uses-permission'].push({ $: { 'android:name': name } });
  }
}

function ensureService(androidManifest) {
  const application = androidManifest.manifest.application?.[0];
  if (!application) return;
  if (!Array.isArray(application.service)) {
    application.service = [];
  }
  const serviceRef = `.${SERVICE_NAME}`;
  const exists = application.service.some(
    (svc) => svc.$ && svc.$['android:name'] === serviceRef
  );
  if (!exists) {
    application.service.push({
      $: {
        'android:name': serviceRef,
        'android:enabled': 'true',
        'android:exported': 'false',
        'android:foregroundServiceType': SERVICE_TYPE,
      },
    });
  }
}

const withManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    FOREGROUND_PERMISSIONS.forEach((perm) => ensurePermission(cfg.modResults, perm));
    ensureService(cfg.modResults);
    return cfg;
  });

function kotlinSource(packageName) {
  return `package ${packageName}

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.Service
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.IBinder
import androidx.core.app.NotificationCompat

/**
 * Started foreground service that keeps the app process resident so that
 * call detection continues while the app is backgrounded. Generated by the
 * withCallForegroundService config plugin — do not edit by hand.
 */
class ${SERVICE_NAME} : Service() {

  companion object {
    private const val CHANNEL_ID = "alphapos_operator_link"
    private const val NOTIFICATION_ID = 7651
  }

  override fun onBind(intent: Intent?): IBinder? = null

  override fun onCreate() {
    super.onCreate()
    startAsForeground()
  }

  override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
    startAsForeground()
    // Restart if the OS kills us while the operator phone stays on.
    return START_STICKY
  }

  private fun startAsForeground() {
    createChannel()

    val notification: Notification = NotificationCompat.Builder(this, CHANNEL_ID)
      .setContentTitle("AlphaPOS Operator Link")
      .setContentText("Listening for calls and linked to the POS desktop.")
      .setSmallIcon(applicationInfo.icon)
      .setOngoing(true)
      .setPriority(NotificationCompat.PRIORITY_LOW)
      .build()

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
      startForeground(
        NOTIFICATION_ID,
        notification,
        ServiceInfo.FOREGROUND_SERVICE_TYPE_DATA_SYNC
      )
    } else {
      startForeground(NOTIFICATION_ID, notification)
    }
  }

  private fun createChannel() {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
      val manager = getSystemService(NotificationManager::class.java)
      if (manager != null && manager.getNotificationChannel(CHANNEL_ID) == null) {
        val channel = NotificationChannel(
          CHANNEL_ID,
          "Operator Link",
          NotificationManager.IMPORTANCE_LOW
        )
        channel.setShowBadge(false)
        manager.createNotificationChannel(channel)
      }
    }
  }
}
`;
}

const withServiceSource = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const packageName = cfg.android?.package;
      if (!packageName) {
        throw new Error(
          'withCallForegroundService: android.package is required in app.json.'
        );
      }
      const projectRoot = cfg.modRequest.platformProjectRoot;
      const javaDir = path.join(
        projectRoot,
        'app',
        'src',
        'main',
        'java',
        ...packageName.split('.')
      );
      fs.mkdirSync(javaDir, { recursive: true });
      fs.writeFileSync(
        path.join(javaDir, `${SERVICE_NAME}.kt`),
        kotlinSource(packageName),
        'utf8'
      );
      return cfg;
    },
  ]);

const withServiceAutostart = (config) =>
  withMainActivity(config, (cfg) => {
    const packageName = config.android?.package;
    if (!packageName) return cfg;

    let contents = cfg.modResults.contents;
    if (contents.includes(SERVICE_NAME)) {
      // Already injected on a previous prebuild.
      return cfg;
    }

    const isKotlin = cfg.modResults.language === 'kt';
    const startCall = isKotlin
      ? `\n    androidx.core.content.ContextCompat.startForegroundService(this, android.content.Intent(this, ${packageName}.${SERVICE_NAME}::class.java))`
      : `\n    androidx.core.content.ContextCompat.startForegroundService(this, new android.content.Intent(this, ${packageName}.${SERVICE_NAME}.class));`;

    if (contents.includes('super.onCreate(null)')) {
      contents = contents.replace(
        'super.onCreate(null)',
        `super.onCreate(null)${startCall}`
      );
    } else {
      // Fallback for templates that forward savedInstanceState.
      contents = contents.replace(
        /super\.onCreate\(([^)]*)\)/,
        (match) => `${match}${startCall}`
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });

/** @param {import('@expo/config-plugins').ExpoConfig} config */
module.exports = function withCallForegroundService(config) {
  config = withManifest(config);
  config = withServiceSource(config);
  config = withServiceAutostart(config);
  return config;
};
