/** Shared, token-safe view models for the native operator service. */
/** Operator POS show the incoming-call popup; cashier POS only offer the caller's number for quick entry. */
export type PosRole = 'operator' | 'cashier';

export interface SavedPos {
  id: string;
  name: string;
  url: string;
  discoveryPort?: number;
  role?: PosRole;
}

export interface TelegramSettings {
  enabled: boolean;
  /** Only present while submitting a changed token. Native storage encrypts it. */
  botToken?: string;
  chatId: string;
  folderUri: string;
  folderName: string;
  sendMissedCalls?: false;
  statsChatId?: string;
  sendCallStats?: boolean;
  /** Copy of everything the bot sends, so deleted messages are never lost. */
  backupChatId?: string;
}

/** Local time "HH:MM"; an end at or before the start finishes on the next day. */
export interface ShiftConfig {
  index: number;
  name: string;
  start: string;
  end: string;
}

export type ManagerSchedule =
  | { type: 'fixed'; shift: number }
  /** Weekly rotation: in the week starting on Sunday `anchorWeekStart` the manager works `anchorShift`. */
  | { type: 'rotating'; anchorWeekStart: number; anchorShift: number };

export interface ManagerConfig {
  id: string;
  name: string;
  phone: string;
  schedule: ManagerSchedule;
  /** Private Telegram invite code; generated by the phone service. */
  invite?: string;
  sms: boolean;
  telegram: boolean;
}

export interface ClosedSmsConfig {
  enabled: boolean;
  text: string;
}

export interface AlertConfig {
  managerAfterMinutes: number;
  lostAfterMinutes: number;
  smsDailyCap: number;
}

export interface OperatorConfiguration {
  targets: SavedPos[];
  telegram: TelegramSettings;
  shifts?: ShiftConfig[];
  closedSms?: ClosedSmsConfig;
  alerts?: AlertConfig;
  managers?: ManagerConfig[];
}

export interface OperatorOperations {
  outboxPending?: number;
  outboxError?: string | null;
  lastSentAt?: number;
  smsToday?: number;
  smsError?: string | null;
  smsPermission?: boolean;
  botUsername?: string;
  botError?: string | null;
  managerChats?: Record<string, string>;
  backupSince?: number;
}

export interface RuntimePeriod {
  startedAt: number;
  endedAt: number | null;
  endReason?: string;
  approximate?: boolean;
}

/** Native self-update state (GitHub releases, installed between calls). */
export interface UpdateStatus {
  installedCode: number;
  installedName: string;
  state: 'idle' | 'checking' | 'downloading' | 'ready' | 'installing' | 'installed' | 'waiting_user' | 'error';
  latestCode: number;
  latestName: string;
  notes: string;
  lastCheckAt: number;
  nextCheckAt: number;
  downloaded: number;
  size: number;
  error: string;
  canInstallPackages: boolean;
}

export interface RuntimeSnapshot {
  update?: UpdateStatus;
  operations?: OperatorOperations;
  running: boolean;
  startedAt: number | null;
  lastHeartbeatAt: number | null;
  lastError?: string;
  phonePermission?: boolean;
  targets: (SavedPos & {
    status: 'connected' | 'connecting' | 'disconnected';
    lastConnectedAt?: number;
    error?: string;
  })[];
  periods: RuntimePeriod[];
  telegram: {
    enabled: boolean;
    configured: boolean;
    hasToken?: boolean;
    statsChatId?: string;
    sendCallStats?: boolean;
    statsPending?: number;
    statsError?: string;
    statsLastSentAt?: number;
    backupChatId?: string;
    outboxPending?: number;
    folderUri: string;
    folderName: string;
    pending: number;
    sent: number;
    lastSentAt?: number;
    lastError?: string;
  };
}

/** A folder in the phone's shared storage, read directly with "All files access". */
export interface RecordingFolder {
  uri: string;
  path: string;
  /** Path relative to internal storage, e.g. `Recordings/Call`; empty for the storage root. */
  name: string;
  audioCount: number;
  latestAudioAt: number;
  truncated?: boolean;
}

export interface FolderListing extends RecordingFolder {
  isRoot: boolean;
  parent: string | null;
  folders: { path: string; name: string }[];
}

export function recordingFolderLabel(folder: Pick<RecordingFolder, 'name'>): string {
  return folder.name ? `Ichki xotira/${folder.name}` : 'Ichki xotira';
}

export const EMPTY_TELEGRAM: TelegramSettings = {
  enabled: false, chatId: '', folderUri: '', folderName: '', sendMissedCalls: false,
};

export const DEFAULT_SHIFTS: ShiftConfig[] = [
  { index: 1, name: '1-smena', start: '08:00', end: '17:00' },
  { index: 2, name: '2-smena', start: '17:00', end: '02:00' },
];
export const DEFAULT_CLOSED_SMS = "Smart Food kafesi hozir ishlamayapti. Ish vaqtimiz: har kuni 08:00 dan 02:00 gacha. Qo'ng'iroq qilganingiz uchun rahmat!";
export const DEFAULT_ALERTS: AlertConfig = { managerAfterMinutes: 1, lostAfterMinutes: 5, smsDailyCap: 50 };
const DAY_MS = 86_400_000;

export function isClock(value: string): boolean {
  return /^([01]?\d|2[0-3]):[0-5]\d$/.test(value.trim());
}

const MOBILE_CODES = new Set(['20', '33', '50', '55', '77', '88', '90', '91', '93', '94', '95', '97', '98', '99']);

function uzDigits(value: string): string {
  let digits = value.replace(/\D/g, '');
  if (digits.startsWith('00')) digits = digits.slice(2);
  return digits.length === 9 ? `998${digits}` : digits;
}

/** Same rule as the native SMS sender: +998 and a mobile operator code. */
export function isUzbekMobile(value: string): boolean {
  const digits = uzDigits(value);
  return digits.length === 12 && digits.startsWith('998') && MOBILE_CODES.has(digits.slice(3, 5));
}

export function formatUzPhone(value: string): string {
  const digits = uzDigits(value);
  if (digits.length !== 12) return value.trim();
  return `+998 ${digits.slice(3, 5)} ${digits.slice(5, 8)} ${digits.slice(8, 10)} ${digits.slice(10)}`;
}

/** Local Sunday 00:00 of the week containing `at`. */
export function weekStart(at: number): number {
  const date = new Date(at);
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() - date.getDay());
  return date.getTime();
}

/** The shift index a manager works in the week that starts on `week` (mirrors the native rule). */
export function managerShiftForWeek(schedule: ManagerSchedule, week: number, shifts: ShiftConfig[]): number | null {
  if (schedule.type === 'fixed') return schedule.shift;
  const anchor = shifts.findIndex((shift) => shift.index === schedule.anchorShift);
  if (anchor < 0 || shifts.length === 0) return null;
  const weeks = Math.round((weekStart(week) - weekStart(schedule.anchorWeekStart)) / (7 * DAY_MS));
  return shifts[(((anchor + weeks) % shifts.length) + shifts.length) % shifts.length]!.index;
}

export function managerInviteLink(botUsername: string | undefined, invite: string | undefined): string | null {
  if (!botUsername || !invite) return null;
  return `https://t.me/${botUsername}?start=${invite}`;
}

function boundedInt(value: unknown, fallback: number, min: number, max: number): number {
  return typeof value === 'number' && Number.isInteger(value) && value >= min && value <= max ? value : fallback;
}

/** Trust nothing from storage: every optional section gets a valid shape. */
export function normalizeConfiguration(raw: Partial<OperatorConfiguration> | null | undefined): OperatorConfiguration {
  const value = raw ?? {};
  const shifts = Array.isArray(value.shifts)
    ? value.shifts.filter((s): s is ShiftConfig => !!s && typeof s.name === 'string' && isClock(String(s.start)) && isClock(String(s.end)) && Number.isInteger(s.index))
    : [];
  const managers: ManagerConfig[] = Array.isArray(value.managers)
    ? value.managers.filter((m): m is ManagerConfig => !!m && typeof m.id === 'string' && typeof m.name === 'string' && !!m.schedule)
      .map((m) => ({ ...m, phone: typeof m.phone === 'string' ? m.phone : '', sms: m.sms !== false, telegram: m.telegram !== false }))
    : [];
  const alerts: Partial<AlertConfig> = value.alerts ?? DEFAULT_ALERTS;
  return {
    targets: Array.isArray(value.targets) ? value.targets.map((t) => ({ ...t, role: t.role === 'cashier' ? 'cashier' as const : 'operator' as const })) : [],
    telegram: safeTelegramSettings(value.telegram ?? EMPTY_TELEGRAM),
    shifts: shifts.length ? shifts : DEFAULT_SHIFTS,
    closedSms: {
      enabled: value.closedSms?.enabled === true,
      text: typeof value.closedSms?.text === 'string' && value.closedSms.text.trim() ? value.closedSms.text : DEFAULT_CLOSED_SMS,
    },
    alerts: {
      managerAfterMinutes: boundedInt(alerts.managerAfterMinutes, 1, 1, 60),
      lostAfterMinutes: boundedInt(alerts.lostAfterMinutes, 5, 1, 240),
      smsDailyCap: boundedInt(alerts.smsDailyCap, 50, 0, 500),
    },
    managers,
  };
}

const INVALID_QR = 'Bu POS ulanish kodi emas. POSdagi operator tugmasini bosib turing va QR kodni skanerlang.';

/** Validate without the incomplete URL implementation on older React Native. */
export function inspectPosUrl(value: string): { host: string; token: string } {
  const match = /^(wss?):\/\/(\[[0-9a-f:]+\]|[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?)(?::([0-9]{1,5}))?(\/[^?#\s]*)?\?([^#\s]+)$/i.exec(value);
  if (!match || value.length > 2048) throw new Error(INVALID_QR);
  if (match[3] && (Number(match[3]) < 1 || Number(match[3]) > 65535)) throw new Error(INVALID_QR);
  const parts = match[5]!.split('&');
  const tokenParts = parts.filter((part) => part.split('=')[0] === 'token');
  if (tokenParts.length !== 1) throw new Error(INVALID_QR);
  let token: string;
  try { token = decodeURIComponent(tokenParts[0]!.slice(6)); } catch { throw new Error(INVALID_QR); }
  if (!/^[A-Za-z0-9._~-]{1,256}$/.test(token)) throw new Error(INVALID_QR);
  return { host: match[2]!, token };
}

/** Legacy IDs are opaque: never show a pairing token as an identifier. */
function legacyId(value: string): string {
  let a = 2166136261;
  let b = 5381;
  for (let i = 0; i < value.length; i += 1) {
    a = Math.imul(a ^ value.charCodeAt(i), 16777619);
    b = Math.imul(b, 33) ^ value.charCodeAt(i);
  }
  return `legacy-${(a >>> 0).toString(16)}${(b >>> 0).toString(16)}`;
}

export function parsePairingCode(scanned: string): SavedPos {
  const raw = scanned.trim();
  if (raw.length > 4096) throw new Error(INVALID_QR);
  if (/^wss?:\/\//i.test(raw)) {
    const { host, token } = inspectPosUrl(raw);
    return { id: legacyId(token), name: `POS · ${host}`, url: raw };
  }
  let value: Record<string, unknown>;
  try { value = JSON.parse(raw); } catch { throw new Error(INVALID_QR); }
  if (!value || value.version !== 2 || typeof value.id !== 'string' ||
      !/^[A-Za-z0-9_-]{1,128}$/.test(value.id) || typeof value.name !== 'string' ||
      !value.name.trim() || value.name.length > 128 || typeof value.url !== 'string') {
    throw new Error(INVALID_QR);
  }
  inspectPosUrl(value.url);
  if (value.discoveryPort !== undefined &&
      (!Number.isInteger(value.discoveryPort) || Number(value.discoveryPort) < 1 || Number(value.discoveryPort) > 65535)) {
    throw new Error(INVALID_QR);
  }
  return {
    id: value.id, name: value.name.trim(), url: value.url,
    ...(value.discoveryPort === undefined ? {} : { discoveryPort: Number(value.discoveryPort) }),
  };
}

/** Rescanning updates a POS instead of making a second recipient. */
export function upsertPos(targets: SavedPos[], next: SavedPos): SavedPos[] {
  const token = inspectPosUrl(next.url).token;
  const index = targets.findIndex((target) =>
    target.id === next.id || inspectPosUrl(target.url).token === token);
  if (index < 0) return [...targets, next];
  return targets.map((target, i) => i === index ? next : target);
}

export function safeTelegramSettings(settings: Partial<TelegramSettings>): TelegramSettings {
  return {
    enabled: settings.enabled === true,
    chatId: typeof settings.chatId === 'string' ? settings.chatId.trim() : '',
    folderUri: typeof settings.folderUri === 'string' ? settings.folderUri : '',
    folderName: typeof settings.folderName === 'string' ? settings.folderName : '',
    sendMissedCalls: false,
    statsChatId: typeof settings.statsChatId === 'string' ? settings.statsChatId.trim() : '',
    sendCallStats: settings.sendCallStats === true,
    backupChatId: typeof settings.backupChatId === 'string' ? settings.backupChatId.trim() : '',
  };
}

/** Private provisioning QR. Credentials go straight to encrypted native storage. */
export function parseTelegramSetupCode(scanned: string): Pick<TelegramSettings, 'botToken' | 'chatId' | 'statsChatId' | 'backupChatId'> {
  const invalid = 'Telegram sozlash QR kodi noto‘g‘ri.';
  let value: Record<string, unknown>;
  try { value = JSON.parse(scanned); } catch { throw new Error(invalid); }
  const group = (id: unknown): id is string => typeof id === 'string' && /^-[0-9]+$/.test(id);
  if (!value || value.type !== 'smart_pos_telegram' || (value.version !== 1 && value.version !== 2) ||
      typeof value.botToken !== 'string' || !/^[0-9]{5,}:[A-Za-z0-9_-]{20,}$/.test(value.botToken) ||
      !group(value.chatId) || !group(value.statsChatId) || value.chatId === value.statsChatId ||
      (value.backupChatId !== undefined && (!group(value.backupChatId) || value.backupChatId === value.chatId || value.backupChatId === value.statsChatId))) {
    throw new Error(invalid);
  }
  return {
    botToken: value.botToken, chatId: value.chatId, statsChatId: value.statsChatId,
    ...(group(value.backupChatId) ? { backupChatId: value.backupChatId } : {}),
  };
}
